#!/usr/bin/env python3
from symbols import *
board=[
'X','O',' ',
' ','X',' ',
' ',' ','O']
def printBoard(board):
    print(tlcor+3*hline+tedge+3*hline+tedge+3*hline+trcor)
    print(vline+' '+board[0]+' '+vline+' '+board[1]+' '+vline+' '+board[2]+' '+vline)
    print(ledge+3*hline+cross+3*hline+cross+3*hline+redge)
    print(vline+' '+board[3]+' '+vline+' '+board[4]+' '+vline+' '+board[5]+' '+vline)
    print(ledge+3*hline+cross+3*hline+cross+3*hline+redge)
    print(vline+' '+board[6]+' '+vline+' '+board[7]+' '+vline+' '+board[8]+' '+vline)
    print(blcor+3*hline+bedge+3*hline+bedge+3*hline+brcor)
printBoard(board)
